apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:   #doit etre encodé en base64 donc echo -n "d4f_db" | base64
  POSTGRES_DB: ZDhmX2Ri
  POSTGRES_USER: ZDhmX3VzZXI=
  POSTGRES_PASSWORD: ZDhmX3Bhc3N3b3Jk