apiVersion: v1
kind: Secret
metadata:
  name: d4f-secrets
type: Opaque
data:   #doit etre encodé en base64 donc echo -n "d4f_db" | base64
  POSTGRES_DB: ZDRmX2Ri
  POSTGRES_USER: ZDRmX3VzZXI=
  POSTGRES_PASSWORD: ZDRmX3Bhc3N3b3Jk
  FLASK_db_user: ZDRmX3VzZXI=
  FLASK_db_pass: ZDRmX3Bhc3N3b3Jk