name: Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'D4F_front/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'D4F_front/**'
  workflow_dispatch:  # ⬅️ permet de lancer manuellement dans l’UI

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      working-directory: ./D4F_front
      run: npm install

    - name: Build frontend
      working-directory: ./D4F_front
      run: npm run build
